#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant
  customize:
    memory: <%= ENV['TEST_KITCHEN_VM_MEMORY'] || 2048 %>
    cpus: <%= ENV['TEST_KITCHEN_VM_CPUS'] || 2 %>
  network:
    - ["private_network", {ip: "172.31.6.12"}]

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  roles_path: test/fixtures/roles
  environments_path: test/fixtures/environments
  client_rb:
    environment: testkitchen

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: php5_package
    run_list:
      - role[w_common_role]
      - role[w_apache_role]
  - name: php5_source
    run_list:
      - role[w_common_role]
      - role[w_apache_role]
    attributes: {
      "php": {
        "install_method": "source"
      }
    }
